[DEFAULT]
output_folder = .

[SEARCH_CONFIG]
# Format: filename:"Nama File" after:YYYY/MM/DD before:YYYY/MM/DD - dan atau menggunakan query dibawah (terbaru)
# Mencari semua email dari domain shell.com yang memiliki lampiran PDF dalam rentang tanggal
gmail_query = from:*@shell.com has:attachment filename:pdf after:2026/05/01 before:2026/07/31

# Format: YYYY-MM-DD
strict_start_date = 2026-05-01
strict_end_date   = 2026-07-31

# Karena nama file yang diunduh berupa angka acak (misal: 1480817404.pdf)
# bagian pengecekan nama file di Python harus dipastikan tidak menyaring kata kunci apa pun jika filename_must_contain dikosongkan.
# atau di isi, contoh: "filename_must_contain = Faktur Penjualan"
filename_must_contain =